export const relatedKeywordsData = [
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
  {
    keyword: "Chocolate Cake",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
];

export const keywordData = [
  {
    keyword: "Chocolate Ice Cream",
    competition_index: 0,
    "High CPC": 0,
    "Low CPC": 0,
    avg_monthly_searches: 0,
    competition_value: 0,
    volume: 0,
  },
];
